### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by yangzhou04** [myleott/JGibbLabeledLDA#1]
After some warning of "Unknown document label ( term ) for document doc_id."
An exception occurs:

java.lang.ArrayIndexOutOfBoundsException: 116
    at jgibblda.Estimator.sampling(Estimator.java:114)
    at jgibblda.Estimator.estimate(Estimator.java:66)
    at jgibblda.LDA.main(LDA.java:52)

My data like:
[10] term1_1 term1_2 ...
term_2_1 term2_2 ...

**Comment by yangzhou04** [comment]
I've found the reason, that's because the topic number should larger than the label index size.

Although it seems obvious, it's better to explain it in the readme.
